### ISSUE TITLE
RPI 2 problems with wm8731

### ISSUE THREAD

**Issue by Shibonja** [mxmxmx/terminal_tedium#1]
Hi,

Nice work you have done with the sound mixer. Can I ask you which version of raspbian you are using. I downloaded Raspbian Jessie (kernel version 4.1.18-v7+) and can't get my wm8731 working. 
I am getting these errors in dmesg:

``` bash
[    6.100440]snd-rpi-proto sound: ASoC: CPU DAI (null) not registered
[    6.100462] snd-rpi-proto sound: snd_soc_register_card() failed: -517
[    6.100963] snd-rpi-proto sound: ASoC: CPU DAI (null) not registered
[    6.100989] snd-rpi-proto sound: snd_soc_register_card() failed: -517
[    6.102795] bcm2708_i2c 3f804000.i2c: BSC1 Controller at 0x3f804000 (irq 79) (baudrate 100000)
[    6.103079] snd-rpi-proto sound: ASoC: CPU DAI (null) not registered
[    6.103091] snd-rpi-proto sound: snd_soc_register_card() failed: -517
[    6.105641] snd-rpi-proto sound: ASoC: CODEC DAI wm8731-hifi not registered
[    6.105654] snd-rpi-proto sound: snd_soc_register_card() failed: -517
```

Regards, Haris

**Comment by Shibonja** [comment]
Hi, I got playback working.  But sound recording doesn't work, have you experience with sound recording.

**Comment by mxmxmx** [comment]
Hi Haris,

I haven't done any nice work with the sound mixer (?), but observing [this](https://github.com/mxmxmx/terminal_tedium/wiki/DAC#3-amixer) should be enough to get the inputs working.

**Comment by mxmxmx** [comment]
As this seems to be about mikroelektronika boards, not terminal tedium, I'm closing this Issue.
