### ISSUE TITLE
compiling externals for osx (the osx-dummies files)

### ISSUE THREAD

**Issue by michaelpalumbo** [mxmxmx/terminal_tedium#10]
Hi there,

I've not been successful at compiling the externals you've provided for developing pd patches using osx. Using the gcc command you provided:

```shell
gcc -std=c99 -O3 -Wall -c [name_of_external].c -o [name_of_external].o
```

I get:

```shell
gcc: warning: tedium_input/tedium_input.pd_darwin: linker input file unused because linking not done
```

Is there something I'm doing wrong, or, is it possible to share pre-compiled externals? thanks!

**Comment by JMC64** [comment]
Hi, why would you compile the externals on osx when the files are for RPI? Either you cross compile them on osx for rpi (good luck!) or you directly compile them on the rpi. You can directly create your patchs on rpi with Xorg installed on it and once happy with them, run them  with no-GUI. Hope this helps.

**Comment by michaelpalumbo** [comment]
thanks @JMC64, but I understood the [osx-dummies files](https://github.com/mxmxmx/terminal_tedium/tree/master/software/externals/osx_dummies) to mean that I could develop pd patches on OSX and then run them with nogui on raspbian. I found the osx externals using the tt template provided by https://github.com/NorthCoastModularCollective/Terminal-Tedium-Pd-Patches

Anyway, for future users it'd be really nice to have some documentation on how to compile the osx externals.

**Comment by bsom** [comment]
I'm confused.  Compiled versions of the osx dummies are already available here.

Inside of each dummies folder is a 'darwin' compiled dummy: https://github.com/mxmxmx/terminal_tedium/tree/master/software/externals/osx_dummies/tedium_input

**Comment by michaelpalumbo** [comment]
I see, well thanks for clearing this up! I used to use pd all the time and so I clearly forgot that .pd_darwin was the extension for osx externals. 

for what its worth, I got confused by the text under osx_dummies "same thing, but non-functional ... for use on osx." I assumed the 'same thing' was referring to the need to compile them. 

> compile with:
> 
> gcc -std=c99 -O3 -Wall -c [name_of_external].c -o [name_of_external].o
> 
> ld --export-dynamic -shared -o [name_of_external].pd_linux [name_of_external].o -lc -lm -lwiringPi
> 
> then move things into externals folder, eg:
> 
> sudo mv [name_of_external].pd_linux /usr/lib/pd/extra/
> 
> osx_dummies
> 
> same thing, but non-functional ... for use on osx.
