### ISSUE TITLE
OSC receive to set LED + GATEs

### ISSUE THREAD

**Issue by JnsVttr** [mxmxmx/terminal_tedium#13]
I am using SuperCollider instead of PD on the Terminal Tedium with piCore, so I am using the OSC client to communicate - it would so be great, **if the OSC client could not only send values, but also receive messages to set LED, GATE1 and GATE2**. would this be easily possible to embed? 

Right now I am using an additional osc4py3 server to receive messages from SuperCollider and to set the LEDs and GATEs, which is of course not very convenient. I am not good in C, but maybe you have a suggestion how to adapt the OSC client to receive messages?

**Comment by JMC64** [comment]
Hello, 

I just wrote an OSC client + server. It is available on my github. Gate and leds should work. Please let me know if you test it.
https://github.com/JMC64/Terminal-Tedium-/tree/master/OSC_receiver

**Comment by JnsVttr** [comment]
> I just wrote an OSC client + server. It is available on my github. Gate and leds should work. Please let me know if you test it.
> https://github.com/JMC64/Terminal-Tedium-/tree/master/OSC_receiver

great! I am trying to get it running on piCore. But I am stuck in the dependencies: I managed to build liblo, but I have problems with building liblo-dev. 
Still searching for a solution..

**Comment by JMC64** [comment]
Hello, 

You don't need to install liblo-dev. This is a package for the debian distribution.
If you built the liblo library and installed it , (i.e.  make && sudo make install), the OSC client should build easily. Just  type "make all" 

hope this helps 


----- Mail original -----
De: "Jens Vetter" <notifications@github.com>
À: "mxmxmx/terminal_tedium" <terminal_tedium@noreply.github.com>
Cc: "JMC64" <jeanmarc.chourot@free.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Jeudi 2 Avril 2020 17:11:03
Objet: Re: [mxmxmx/terminal_tedium] OSC receive to set LED + GATEs (#13)







I just wrote an OSC client + server. It is available on my github. Gate and leds should work. Please let me know if you test it. 
https://github.com/JMC64/Terminal-Tedium-/tree/master/OSC_receiver 

great! I am trying to get it running on piCore. But I am stuck in the dependencies: I managed to build liblo, but I have problems with building liblo-dev. 
Still searching for a solution..

**Comment by JnsVttr** [comment]
hey thanks a lot! now I managed to get it working on piCore. 
Works like a charm - great work!

only one weird thing with liblo library.. what I did to install it on piCore:

```
cd ~/
tce-load -wi libtool.tcz automake.tcz autoconf.tcz
#install liblo: 
git clone git://liblo.git.sourceforge.net/gitroot/liblo/liblo
cd liblo
sudo ./ autogen.sh
sudo ./configure
sudo make && sudo make install
```

then your repo:
```
cd ~/
git clone https://github.com/JMC64/Terminal-Tedium-/
cd Terminal-Tedium-/OSC_receiver
make all
```
now if I try to `sudo ./OSC_client_server `, I get thtis error:
` error while loading shared libraries: liblo.so.7: cannot open shared object file: No such file or directory`

As far as I understand it has to do with the PATH, so I exported it in `~/.bashrc`:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
source /usr/local/etc/bashrc 
```

Nothing changed. And  really the only way I can get the OSC_client_server running is by:

`sudo LD_LIBRARY_PATH=/usr/local/lib/ ./OSC_client_server `

Which is anyway fine for me, since this command will go in the autostart script. 

So far, thanks again!!
