### ISSUE TITLE
DC Coupled Audio Output to use as CV?

### ISSUE THREAD

**Issue by bsom** [mxmxmx/terminal_tedium#2]
It is stated here: https://github.com/mxmxmx/terminal_tedium/wiki/wm8731
that the audio outputs are "simple inverting amplifier with ~ 4.75x gain; outputs are DC blocked".

Is there a modification/edit/hack that could be done so that the audio outs are actually able to produce something closer to DC-coupled CV?

**Comment by synthbytes** [comment]
DC blocked means there is a capacitor terminating the output and will only let AC pass. To allow DC you'd remove the cap.

**Comment by bsom** [comment]
I understand that, but without a schematic, it is hard for me to be sure I am removing the correct part.

**Comment by mxmxmx** [comment]
... the link above comes with the relevant schematic snippet (?) --https://github.com/mxmxmx/terminal_tedium/wiki/wm8731#output-stage

or what else would you need ? fwiw, the caps in question are the through-hole ones on the top side of the board.

**Comment by bsom** [comment]
Thanks for the hint about the through-hole electrolytic caps.
