### ISSUE TITLE
PiCore requires wiringPi-Dev to be installed to compile Externals

### ISSUE THREAD

**Issue by bsom** [mxmxmx/terminal_tedium#4]
In order to compile the Externals on PiCore, wiringPi-Dev is required.  It contains the headers for wiringPi.  I don't know if this is true for 'regular' RaspPi distributions, but I needed to do it with PiCore 8.x and 9.0.

**Comment by mxmxmx** [comment]
ok, thanks -- added it to the how-to (which i guess could need an update)

**Comment by bsom** [comment]
I'm about to construct an additional T_T using piCore 9.0.  I'll make notes about where the instructions for piCore need updating and submit another issue with potential changes.

**Comment by mxmxmx** [comment]
cool, that would be great ("could need an update" was more like a note to myself though!)
