### ISSUE TITLE
compatible with raspberry pi 4 B?

### ISSUE THREAD

**Issue by michaelpalumbo** [mxmxmx/terminal_tedium#9]
Hi there, exciting project!

Is this by any chance compatible with the newer raspberry pi model 4 B?

Thanks!

**Comment by mxmxmx** [comment]
in terms of pin usage/signals, yes ("[Complete compatibility with earlier Raspberry Pi products](https://www.raspberrypi.org/blog/raspberry-pi-4-on-sale-now-from-35/)"). in terms of power requirements, pi 4 may begin stretching things a little (RECOM 785.0 1.0 = 1.0A; they recommend using 3.0A). that said, you can just power the pi 4 separately, simply remove the [jumper](https://github.com/mxmxmx/terminal_tedium/wiki/wm8731#power) to disconnect the SoC from the onboard 5V.

**Comment by michaelpalumbo** [comment]
@mxmxmx well thats rad! and also kinda cool that the TT wouldn't take up a power port from my euro supply. thanks!
